// <auto-generated />
using System;
using API.NET6.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.NET6.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220425020701_relacionamento")]
    partial class relacionamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.NET6.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.HasKey("IdCargo");

                    b.HasIndex("IdSetor");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("API.NET6.Models.Colaborador", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Admissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Gestor")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdSetor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("Salario")
                        .HasColumnType("float");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Matricula");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdSetor");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("API.NET6.Models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSetor");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("API.NET6.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nome")
                        .HasColumnOrder(2);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API.NET6.Models.Cargo", b =>
                {
                    b.HasOne("API.NET6.Models.Setor", "Setor")
                        .WithMany("Cargos")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("API.NET6.Models.Colaborador", b =>
                {
                    b.HasOne("API.NET6.Models.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.NET6.Models.Setor", "Setor")
                        .WithMany("Colaboradores")
                        .HasForeignKey("IdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("API.NET6.Models.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("API.NET6.Models.Setor", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
